language: node_js
node_js:
- '8'
# sude: required
# services:
#   - docker
cache:
  yarn: true
  directories:
    - node_modules
after_success:
  - yarn coverage
deploy:
  provider: npm
  email: toxictoxer@gmail.com
  api_key:
    secure: VzEnB8CHuHE7qAXnuWwbS5BsAkVjrnoJQBJwHlrhjERsnaCJkg93l4Bac+abUtR96cuWSPfqlCtQCN1wvix/oaJ/MnpA24f57BI35QKNRmIhWxFpFW5D4sLhkTQkcJBqUn91K8CAR+/FUoJgIXXnMWbezNqDU6lQ6Guf8Scnt8yP9L6iabkrawenpjm8XY4b5EjDQyesxPUEIZOuK7z/Zb3kcpPxXwZN+z4GOnQpnA2G3Np7ID/NegZ7TI8IrpRtRzCpo+qEvKUBJpuvfwhbzzFNO9xR0iA6e4cIvRSL4uxJhKCE1LmFnQR4nJOUsu8ufZbLduCLAXIso6sAoFVDBTqzygSRMgoEI7SGYqERGQSNkhpw7DspaMHzIddJiQWJIOYeqrd2auzzIa06G5Aq9PJk2v0Q8tgTgB7K7HJYQhF5RJk7Q37edywz2xozjNYtToQIQQW66C6CYs4fc0A4D8SJe13lZcOR/SFSCJ+aCIdP18M8HgbE/Dercwv9A4Rwh1FqyUzg9KQrPHjVvr/YekTmT9vwa6vfuMUqRJZniF6XBMXyDS//UDeI3y/MQgON6fGnqBmiYgvWv7cBgPFqnbzGlkqTieeZWi9lglSl6D11aXe4S+qNBcC3FWzqOcGTv43gHT5KRP5ge0UL03wn3VhB94INCAPZRBShVR1n2Vc=
  on:
    tags: true
    repo: kthjm/dtz
    branch: publish
